### ISSUE TITLE
Modify the submit handler to allow blocks-inside-blocks

### ISSUE THREAD

**Issue by erral** [collective/collective.volto.formsupport#23]
Currently the form submit endpoint checks if a block is really in the context, but to check that it only [takes into account the `blocks` attribute of the context](https://github.com/collective/collective.volto.formsupport/blob/9006ec0b7d2538d6b89e533c9d545d33da3a5b66/src/collective/volto/formsupport/restapi/services/submit_form/post.py#L165-L176), meaning that if you have a block inside another block (for instance in a column, or a grid), the check will fail and the form can't be submitted.

@gorkafernandez

**Comment by mbarde** [comment]
Should be fixed via: https://github.com/collective/collective.volto.formsupport/pull/29
