### ISSUE TITLE
Handling Frontend requests

### ISSUE THREAD

**Issue by alisedaghatbaf** [collective/collective.volto.formsupport#28]
got the following error while submitting a form. Any clue how to fix this?
![image](https://user-images.githubusercontent.com/31185263/228212390-85186d1f-b04b-4c9d-8d30-b15fd92f0bda.png)

**Comment by cekk** [comment]
Have you installed this product (collective.volto.formsupport) on Plone site? I mean from addons controlpanel.

**Comment by alisedaghatbaf** [comment]
> Have you installed this product (collective.volto.formsupport) on Plone site? I mean from addons controlpanel.

fixed, thanks
